overrides:
  pinia: 2.2.4
catalog:
  '@alova/adapter-uniapp': ^2.0.14
  '@alova/shared': ^1.3.1
  '@antfu/ni': ^25.0.0
  '@dcloudio/types': ^3.4.19
  '@dcloudio/uni-app': 3.0.0-4070520250711001
  '@dcloudio/uni-app-harmony': 3.0.0-4070520250711001
  '@dcloudio/uni-app-plus': 3.0.0-4070520250711001
  '@dcloudio/uni-automator': 3.0.0-4070520250711001
  '@dcloudio/uni-cli-shared': 3.0.0-4070520250711001
  '@dcloudio/uni-components': 3.0.0-4070520250711001
  '@dcloudio/uni-h5': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-alipay': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-baidu': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-jd': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-kuaishou': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-lark': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-qq': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-toutiao': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-weixin': 3.0.0-4070520250711001
  '@dcloudio/uni-mp-xhs': 3.0.0-4070520250711001
  '@dcloudio/uni-quickapp-webview': 3.0.0-4070520250711001
  '@dcloudio/uni-stacktracey': 3.0.0-4070520250711001
  '@dcloudio/vite-plugin-uni': 3.0.0-4070520250711001
  '@iconify-json/carbon': ^1.2.13
  '@iconify-json/heroicons': ^1.2.2
  '@types/fs-extra': ^11.0.4
  '@types/lodash-es': ^4.17.12
  '@uni-helper/uni-app-types': 1.0.0-alpha.6
  '@uni-helper/unocss-preset-uni': ^0.2.11
  '@uni-helper/vite-plugin-uni-components': ^0.2.0
  '@uni-helper/vite-plugin-uni-manifest': ^0.2.8
  '@uni-helper/vite-plugin-uni-pages': ^0.2.29
  '@vue/runtime-core': ~3.4.38
  '@vueuse/core': ^12.8.2
  '@xiaohe01/eslint-config': ^2.2.1
  '@xiaohe01/stylelint-config': ^2.4.0
  '@xiaohe01/tsconfig': ^2.0.0
  alova: ^3.3.4
  await-to-js: ^3.0.0
  dayjs: ^1.11.13
  eslint: ^9.33.0
  esno: ^4.8.0
  fs-extra: ^11.3.1
  husky: ^9.1.7
  lint-staged: ^16.1.5
  lodash-es: ^4.17.21
  miniprogram-api-typings: ^4.1.0
  picoquery: ^2.5.0
  pinia: ~2.2.4
  pinia-plugin-persistedstate: ~4.1.3
  sass: ~1.78.0
  stylelint: ^16.23.1
  terser: ^5.43.1
  typescript: ~5.8.3
  unocss: ~66.0.0
  unocss-applet: ^0.11.0
  unplugin-auto-import: ^20.0.0
  vconsole: ^3.15.1
  vite: ^5.4.19
  vite-plugin-uni-polyfill: ^0.1.0
  vue: ~3.4.38
  vue-tsc: ~2.1.10
  wot-design-uni: ^1.11.0
  z-paging: ^2.8.7
onlyBuiltDependencies:
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - esbuild
  - vue-demi