catalog:
  '@alova/adapter-uniapp': ^2.0.14
  '@alova/shared': ^1.3.1
  '@antfu/ni': ^27.0.0
  '@dcloudio/types': ^3.4.25
  '@dcloudio/uni-app': 3.0.0-4070620250821001
  '@dcloudio/uni-app-harmony': 3.0.0-4070620250821001
  '@dcloudio/uni-app-plus': 3.0.0-4070620250821001
  '@dcloudio/uni-automator': 3.0.0-4070620250821001
  '@dcloudio/uni-cli-shared': 3.0.0-4070620250821001
  '@dcloudio/uni-components': 3.0.0-4070620250821001
  '@dcloudio/uni-h5': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-alipay': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-baidu': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-jd': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-kuaishou': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-lark': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-qq': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-toutiao': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-weixin': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-xhs': 3.0.0-4070620250821001
  '@dcloudio/uni-quickapp-webview': 3.0.0-4070620250821001
  '@dcloudio/uni-stacktracey': 3.0.0-4070620250821001
  '@dcloudio/vite-plugin-uni': 3.0.0-4070620250821001
  '@iconify-json/carbon': ^1.2.14
  '@iconify-json/heroicons': ^1.2.3
  '@types/fs-extra': ^11.0.4
  '@uni-helper/plugin-uni': ^0.1.0
  '@uni-helper/uni-app-types': 1.0.0-alpha.6
  '@uni-helper/uni-env': ^0.2.0
  '@uni-helper/unocss-preset-uni': ^0.2.11
  '@uni-helper/vite-plugin-uni-components': ^0.2.3
  '@uni-helper/vite-plugin-uni-manifest': ^0.2.9
  '@uni-helper/vite-plugin-uni-pages': ^0.3.20
  '@vue/runtime-core': 3.4.21
  '@vueuse/core': ^12.8.2
  '@xiaohe01/eslint-config': ^3.0.0
  '@xiaohe01/stylelint-config': ^2.4.0
  '@xiaohe01/tsconfig': ^2.0.0
  alova: ^3.3.4
  await-to-js: ^3.0.0
  dayjs: ^1.11.18
  es-toolkit: ^1.40.0
  eslint: ^9.38.0
  esno: ^4.8.0
  fs-extra: ^11.3.2
  husky: ^9.1.7
  lint-staged: ^16.2.5
  miniprogram-api-typings: ^4.1.0
  nutui-uniapp: ^1.9.1
  picoquery: ^2.5.0
  pinia: 2.2.4
  pinia-plugin-persistedstate: ~4.1.3
  sass: ~1.78.0
  stylelint: ^16.25.0
  typescript: ~5.8.3
  unocss: ~66.0.0
  unocss-applet: ^0.12.2
  unplugin-auto-import: ^20.2.0
  vconsole: ^3.15.1
  vite: ^5.4.21
  vite-plugin-uni-polyfill: ^0.1.0
  vue: 3.4.21
  vue-tsc: ~2.1.10
  z-paging: ^2.8.8
onlyBuiltDependencies:
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - esbuild
  - vue-demi